chore(gha): add PR branch/repo name check for security reasons

diff --git a/.github/workflows/build-and-publish-docker-artifacts.yaml b/.github/workflows/build-and-publish-docker-artifacts.yaml
--- a/.github/workflows/build-and-publish-docker-artifacts.yaml
+++ b/.github/workflows/build-and-publish-docker-artifacts.yaml
@@ -124,7 +124,12 @@ jobs:
           
           if [ "$TRIGGERING_REF" == "pr" ]
           then
-
+            # At this point cf-gha-baseline has already checked out the PR input and failed the pipeline, but leaving this here for extra safety in case of future changes
+            if [[ ! '${{ github.event.pull_request.head.repo.full_name }}' =~ ^[a-zA-Z0-9._/-]+$ ]] || [[ ! '${{ github.event.pull_request.head.ref }}' =~ ^[a-zA-Z0-9._/-]+$ ]];
+            then
+              echo "[!] Invalid PR branch or repo name (!= ^[a-zA-Z0-9._/-]+\$). Aborting for security reasons."
+              exit 1
+            fi
             if [ "$IS_PR_FROM_FORK" == "true" ]; then
               echo "External PR detected: fetching branch from $PR_HEAD_REPO"
               git fetch https://github.com/${PR_HEAD_REPO}.git "$PR_HEAD_REF"
