chore(gha/npm-audit): swap better-npm-audit for ibm/audit-ci

diff --git a/.github/workflows/dependency-check-npm-audit.yaml b/.github/workflows/dependency-check-npm-audit.yaml
--- a/.github/workflows/dependency-check-npm-audit.yaml
+++ b/.github/workflows/dependency-check-npm-audit.yaml
@@ -37,7 +37,11 @@ jobs:
         npm ci
 
     - name: Run npm audit
-      run: npm audit --json > audit.json
+      run: |
+       # We always save the report so it's uploaded to the Security tab
+       npx audit-ci --report --report-type full --config audit-ci.jsonc -o json > audit.json || true
+       # We run it again in text mode to have a better output in the logs and let it fail if there are vulnerabilities (criticity set in audit-ci.jsonc)
+       npx audit-ci --report --report-type full --config audit-ci.jsonc
 
     - name: Convert npm audit results to SARIF
       if: always()
